apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik
  namespace: default
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      protocol: HTTP
      port: 8000
      allowedRoutes:
        namespaces:
          from: All | Same
#    - name: https
#      protocol: HTTPS
#      port: 8443         # Traefik HTTPS default port
#      tls:
#        mode: Terminate
#        certificateRefs:
#          - name: traefik-tls-secret
#            namespace: default
#      allowedRoutes:
#        namespaces:
#          from: All | Same 
